local report_presenter = require("report_presenter")

local M = {}

M.NOTE_BEGIN = "--- REAPER Audio Tag BEGIN ---"
M.NOTE_END = "--- REAPER Audio Tag END ---"
M.REGION_PREFIX = "Audio Tag: "
M.EXT_REGION_ID = "P_EXT:reaper_audio_tag.region_id"
M.MAX_REGION_TAGS = 3
M.MAX_NOTE_TAGS = 12
M.MAX_REGION_NAME_LENGTH = 180
M.MATCH_EPSILON = 0.01

local function clean_text(value)
  local text = tostring(value or "")
  text = text:gsub("[\r\n\t]+", " ")
  text = text:gsub("%s+", " ")
  return (text:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function percent(score)
  return math.floor((tonumber(score) or 0) * 100 + 0.5)
end

local function approx_equal(left, right, epsilon)
  return math.abs((tonumber(left) or 0) - (tonumber(right) or 0)) <= (epsilon or M.MATCH_EPSILON)
end

local function item_string(item, key, value, set_new_value)
  if not (reaper and reaper.GetSetMediaItemInfo_String) then
    return nil, "This REAPER build does not expose item notes."
  end
  local ok, result = reaper.GetSetMediaItemInfo_String(item, key, value or "", set_new_value == true)
  if ok == false then
    return nil, "Could not access item metadata."
  end
  return result or ""
end

local function selected_item()
  if not (reaper and reaper.CountSelectedMediaItems and reaper.GetSelectedMediaItem) then
    return nil, "REAPER item selection is not available."
  end
  local count = reaper.CountSelectedMediaItems(0)
  if count ~= 1 then
    return nil, "Select the analyzed audio item before writing tags."
  end
  local item = reaper.GetSelectedMediaItem(0, 0)
  if not item then
    return nil, "Could not access the selected item."
  end
  return item
end

local function selected_item_guid(item)
  local guid = item_string(item, "GUID", "", false)
  if guid and guid ~= "" then
    return guid
  end
  return nil
end

local function item_value(item, key)
  if reaper and reaper.GetMediaItemInfo_Value then
    return reaper.GetMediaItemInfo_Value(item, key)
  end
  return nil
end

local function selected_item_matches_result(item, result)
  local expected = result and result.item or {}
  local expected_guid = expected.item_guid
  if expected_guid and expected_guid ~= "" then
    local actual_guid = selected_item_guid(item)
    if actual_guid and actual_guid ~= expected_guid then
      return false, "The selected item is not the analyzed item. Select the analyzed item or run analysis again."
    end
    return true
  end

  if expected.item_position and expected.item_length then
    local actual_position = item_value(item, "D_POSITION")
    local actual_length = item_value(item, "D_LENGTH")
    if not (approx_equal(actual_position, expected.item_position) and approx_equal(actual_length, expected.item_length)) then
      return false, "The selected item does not match the analyzed item. Select the analyzed item or run analysis again."
    end
  end

  return true
end

local function top_predictions(result)
  local vm = report_presenter.view_model(result or {})
  return vm.predictions or {}, vm
end

function M.format_tag(label, score)
  return string.format("%s %d%%", clean_text(label or "Unknown"), percent(score))
end

function M.region_name(result, limit)
  local predictions = top_predictions(result)
  local max_tags = limit or M.MAX_REGION_TAGS
  local tags = {}
  for index, prediction in ipairs(predictions) do
    if index > max_tags then
      break
    end
    tags[#tags + 1] = M.format_tag(prediction.label, prediction.score)
  end

  local name = M.REGION_PREFIX .. (#tags > 0 and table.concat(tags, ", ") or "No confident tags")
  if #name > M.MAX_REGION_NAME_LENGTH then
    name = name:sub(1, M.MAX_REGION_NAME_LENGTH - 3) .. "..."
  end
  return name
end

local function item_range_text(item)
  local position = tonumber(item and item.item_position)
  local selected_end = tonumber(item and item.selected_end)
  local length = tonumber(item and item.item_length)
  if position and not selected_end and length then
    selected_end = position + length
  end
  if position and selected_end then
    return string.format("%.2fs - %.2fs", position, selected_end)
  end
  return "Unknown"
end

function M.notes_block(result, plugin_version, options)
  options = options or {}
  local predictions, vm = top_predictions(result)
  local lines = {
    M.NOTE_BEGIN,
    "Generated by REAPER Audio Tag v" .. tostring(plugin_version or "unknown"),
    "Summary: " .. clean_text(vm.summary or "No summary."),
    "Item range: " .. item_range_text(vm.item),
    "Compute: " .. clean_text(vm.compute or "Unknown"),
    "Tags:",
  }

  local limit = options.max_tags or M.MAX_NOTE_TAGS
  for index, prediction in ipairs(predictions) do
    if index > limit then
      break
    end
    lines[#lines + 1] = string.format("%d. %s", index, M.format_tag(prediction.label, prediction.score))
  end
  if #predictions == 0 then
    lines[#lines + 1] = "No tags were returned."
  end
  lines[#lines + 1] = M.NOTE_END
  return table.concat(lines, "\n")
end

local function join_sections(sections)
  local filtered = {}
  for _, section in ipairs(sections) do
    local text = tostring(section or ""):gsub("^%s+", ""):gsub("%s+$", "")
    if text ~= "" then
      filtered[#filtered + 1] = text
    end
  end
  return table.concat(filtered, "\n\n")
end

function M.replace_notes_block(existing, block)
  local notes = tostring(existing or "")
  local begin_start = notes:find(M.NOTE_BEGIN, 1, true)
  if begin_start then
    local end_start, end_finish = notes:find(M.NOTE_END, begin_start, true)
    if end_start then
      return join_sections({
        notes:sub(1, begin_start - 1),
        block,
        notes:sub(end_finish + 1),
      })
    end
  end
  return join_sections({ notes, block })
end

local function region_with_id(region_id)
  if not (reaper and reaper.EnumProjectMarkers3) then
    return nil
  end
  local numeric_id = tonumber(region_id)
  if not numeric_id then
    return nil
  end
  local index = 0
  while true do
    local retval, is_region, position, region_end, name, marker_id, color = reaper.EnumProjectMarkers3(0, index)
    if not retval or retval == 0 then
      return nil
    end
    if is_region and tonumber(marker_id) == numeric_id then
      return {
        id = numeric_id,
        position = position,
        region_end = region_end,
        name = name or "",
        color = color or 0,
      }
    end
    index = index + 1
  end
end

local function region_is_ours(region)
  return region and tostring(region.name or ""):sub(1, #M.REGION_PREFIX) == M.REGION_PREFIX
end

local function write_region(item, result, region_name)
  if not (reaper and reaper.AddProjectMarker2) then
    return nil, "This REAPER build does not expose project regions."
  end
  local item_position = tonumber((result.item or {}).item_position) or item_value(item, "D_POSITION") or 0
  local selected_end = tonumber((result.item or {}).selected_end)
  local item_length = tonumber((result.item or {}).item_length) or item_value(item, "D_LENGTH") or 0
  if not selected_end then
    selected_end = item_position + item_length
  end

  local saved_region_id = item_string(item, M.EXT_REGION_ID, "", false)
  local existing_region = region_with_id(saved_region_id)
  if region_is_ours(existing_region) and reaper.SetProjectMarker4 then
    reaper.SetProjectMarker4(0, existing_region.id, true, item_position, selected_end, region_name, existing_region.color or 0, 0)
    return existing_region.id, "updated"
  end

  local region_id = reaper.AddProjectMarker2(0, true, item_position, selected_end, region_name, -1, 0)
  if region_id == nil or region_id == false then
    return nil, "Could not create the REAPER Audio Tag region."
  end
  item_string(item, M.EXT_REGION_ID, tostring(region_id), true)
  return region_id, "created"
end

function M.write_result(result, options)
  options = options or {}
  if not result or result.status ~= "ok" then
    return false, "Run analysis successfully before writing tags."
  end

  local item, selection_err = selected_item()
  if not item then
    return false, selection_err
  end

  local matches, match_err = selected_item_matches_result(item, result)
  if not matches then
    return false, match_err
  end

  local notes_block = M.notes_block(result, options.plugin_version)
  local existing_notes, notes_err = item_string(item, "P_NOTES", "", false)
  if existing_notes == nil then
    return false, notes_err
  end
  local next_notes = M.replace_notes_block(existing_notes, notes_block)
  local ok, write_err = item_string(item, "P_NOTES", next_notes, true)
  if ok == nil then
    return false, write_err
  end

  local region_name = M.region_name(result)
  local _, region_status_or_err = write_region(item, result, region_name)
  if region_status_or_err == "created" or region_status_or_err == "updated" then
    return true, "Tags written to item notes and region."
  end
  return false, region_status_or_err
end

function M.write_result_with_undo(result, options)
  options = options or {}
  local undo_name = options.undo_name or "Write REAPER Audio Tag tags to project"
  if reaper and reaper.Undo_BeginBlock then
    reaper.Undo_BeginBlock()
  end
  local ok, message = M.write_result(result, options)
  if reaper and reaper.Undo_EndBlock then
    reaper.Undo_EndBlock(undo_name, -1)
  end
  if ok and reaper and reaper.UpdateArrange then
    reaper.UpdateArrange()
  end
  return ok, message
end

return M
